# Random Forest Classifier 
Practice from sklear doc

In [1]:
from sklearn.model_selection import cross_val_score
from sklearn.datasets import make_blobs
from sklearn.ensemble import RandomForestClassifier

In [2]:
X,y = make_blobs(n_samples=10000,n_features=10,centers=100,random_state=0)

In [3]:
X[:10]

array([[  6.46907649,   4.25070317,  -8.63694437,   4.04478517,
          9.01725363,   4.53587229,  -4.67027643,  -0.48172814,
         -6.44996141,  -2.65984972],
       [  6.48856404,   9.37957037,  10.32791736,  -1.76505523,
         -2.06884193,  -9.53778962,   3.93637985,   3.37542134,
          7.41273719,  -9.72284371],
       [  8.37392753, -10.14342267,  -3.52753613,  -7.33883416,
          1.38555733,   6.96141714,  -4.50445645,  -7.31536045,
         -2.33070872,   6.44087163],
       [ -3.41410113,  -2.01978984,  -2.7481082 ,   4.16869118,
         -5.78865167,  -7.46868472,  -1.71979965,  -5.30265511,
          4.53409855,  -4.61369461],
       [ -1.33002345,  -3.72546538,   9.55999918,  -6.7513564 ,
         -7.40786424,  -2.13151485,   1.76601335,   2.38150639,
         -1.88656804,   8.6673109 ],
       [ -2.71970099,  -3.98067273,   7.18926502,  -6.97399296,
         -0.43887757,  -4.85199468,  -7.20321708,   7.41156213,
          9.68453801,   9.78099117],
       [ -

In [4]:
dir(make_blobs)

['__annotations__',
 '__builtins__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__getstate__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [5]:
RFclF = RandomForestClassifier(n_estimators=10,max_depth=None,min_samples_split=2,random_state=0)

In [6]:
scores = cross_val_score(RFclF,X,y,cv = 5)

In [7]:
scores

array([1.    , 1.    , 0.9995, 1.    , 0.999 ])

In [8]:
scores.mean()

0.9997

In [9]:
type(scores)

numpy.ndarray

# Using Iris Data To Fit Random Forest

In [10]:
import numpy as np
import pandas as pd
from sklearn.model_selection import  train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [11]:
from sklearn.datasets import load_iris

In [12]:
data = load_iris()

In [13]:
dir(data)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [17]:
X = data.data
y = data.target

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.3,random_state=10)

In [19]:
RFclF2 = RandomForestClassifier(n_estimators=50)

In [20]:
RFclF2.fit(X_train,y_train)

RandomForestClassifier(n_estimators=50)

In [21]:
y_pred = RFclF2.predict(X_test)

In [22]:
result = confusion_matrix(y_test,y_pred)

In [23]:
result

array([[14,  0,  0],
       [ 0, 16,  1],
       [ 0,  1, 13]], dtype=int64)

In [24]:
result1 = classification_report(y_test,y_pred)

In [26]:
print(result1)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        17
           2       0.93      0.93      0.93        14

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



In [27]:
resutl2 = accuracy_score(y_test,y_pred)

In [29]:
resutl2

0.9555555555555556